[package]
name = "Right Click Menu Exit"
description = "Exit any menu in the game by right clicking."
repository = "https://github.com/jhaakma/rightClickMenuExit"
authors = [ "Merlord",]
version = "1.1.2"

[dependencies]
assets = [ "MWSE\\mods\\mer\\RightClickMenuExit",]

[dependencies.mwse]
buildnumber = 4093
